### ISSUE TITLE
Why is a fitbit dongle required

### ISSUE THREAD

**Issue by arch-user-france1** [at3560k/fitbit-galileo#1]
Why does it not work with the usual bluetooth adapters?

**Comment by at3560k** [comment]
Hi, this is a fork of a project that I found on bitbucket about 7-8 years ago(see the README).  It looks like it's gone offline since then.  

I can't speak to why it requires a dongle, but I'd speculate that given 7 year old hardware, it's fairly likely that protocols are or were substantially different.

The only change I have made was repairing a cronjob.
